site_name: pycollimator

theme:
  name: material
  # name: readthedocs
  # name: mkdocs
  palette:
    # teal primary can't be used with the teal icon...
    primary: indigo
    accent: teal
  logo: img/icon-192.png
  favicon: img/favicon.ico

plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          # https://mkdocstrings.github.io/python/usage/configuration/general/
          options:
            show_source: true
            show_root_heading: true
            show_root_toc_entry: true
            show_root_full_path: true

nav:
  - index.md
  - API Reference:
      - pycollimator.md
      - wildcat:
          - wildcat/intro.md
          - wildcat/library.md
  - about.md
