name: Build and Publish Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-publish-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install '.[dev]'

      - name: Build and Generate Docs
        run: |
          mkdocs build --clean

      - name: Upload Pages Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          name: pages
          path: path/to/docs/folder
